channels:
  - conda-forge
  - defaults
dependencies:
  - cryptography
  - flake8
  - pip
  - pycodestyle
  - pydocstyle
  - pyserial
  - pyusb
  - sqlite
  - typing_extensions
  - pip:
    - pybricks
    - pybricksdev

